[[GDAL]]
arch = "aarch64"
git-tree-sha1 = "943e652831bb800fecc5e45bc279b883dbc83998"
os = "macos"

    [[GDAL.download]]
    sha256 = "53a6df3b013166df6c830f163ef42821c78191bdb64d19ad222eb958046a8313"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.aarch64-apple-darwin.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8e1741e5d4431e94f0001ac513d8533f2983ad3"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "061cd870f9272a1a82955d1751a7ad0f7853d9b4c58defb780c9c0433e176fd9"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.aarch64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2910d28bb4b43fe105289bf41a628716397c3ece"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "a9f0067dc53d74b221622250f6246a5cff5d773143ec541dc04096fb9a80c1d4"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.aarch64-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "aarch64"
git-tree-sha1 = "b86fec79f1cc2e019c90cd814e20b39a5690fa9c"
os = "freebsd"

    [[GDAL.download]]
    sha256 = "aec1eaeac394237e051a91636319d0713b99ac55a35d64bf7424d1881b197c7f"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.aarch64-unknown-freebsd.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e02fb4bbe611a3ac52003d1642358f7acf4c9b7c"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "75afd3a89235449a6a54c7089876ad32c91dee2b2d4ce90aae37caa3c1b0be87"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edff1747cc50622c5c909adabb13339c58ba651e"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "f834040b81451050efeca607019274ee1d99750575d427619d67184e2f25e5e9"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d31f2716c44997c40adaf468feb87a0897d8d59d"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "e3253ff5930c7fa49e3a9c87eb5ba8f11aecefbb0ebb7ad6e8d4e6e58dd36e46"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c3474eba59eb43111da48b4720e815f6d5f3541"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "c5f6c6cd4430c9274f4271a3f05cdf1b1b1ad263835a6387a408a387edcc144f"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "206bfd48ef20f86d61173b4d904215716e9c669f"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "3371c1f2534c9987be9521c49b4fc663471d9a391a2a95723ae743e807be0c87"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.i686-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54d824d747ad145571f652a08befebf0d8f5123b"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "895c8ed94712b0177b593613a10c016f43c0447730cfbf1e6e882aeb92a994ad"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.i686-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65c6ef0746bd4e60346342a0fa2437c1b964a29d"
os = "windows"

    [[GDAL.download]]
    sha256 = "6d5856f589802766e8e11eb353b256b01b2e6e70157a3f6346c712368912a9ef"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.i686-w64-mingw32-cxx11.tar.gz"
[[GDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d539eb482561649c12131dbfc343385fda6b5b7c"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "0bfbe3851e19d8308678723f10c53a7e0dd1b87b1683070da65fcf237d7cf123"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c624e103d54aa9f1ee9f1e092eee728f1c76147"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "f7a9998cdf864521499daebcae51db14a6f4db309c89748fa8ef56d835dfa429"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.riscv64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
git-tree-sha1 = "f20af4055e73e60b90bd34a0b030b693982af214"
os = "macos"

    [[GDAL.download]]
    sha256 = "8164847cfadb86453d3c7f714ef52b099d1b145b1675440e753db252dc2d0a21"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.x86_64-apple-darwin.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41d2388168ab57f16056b8bd78500e4c96508f6e"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "4fd45c191230dd2afe523a46ff6c815641e6c10a915de295ac6aaf69938a13d8"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.x86_64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc519e1dcfd9143b0dbb34f1d1be75b233b9cf9a"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "1005e606af850da67d911d64736c145113a335116b576a73dba588a65caaf196"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.x86_64-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
git-tree-sha1 = "b6ae9e060ce09ea24fc39f04849af71d4e732996"
os = "freebsd"

    [[GDAL.download]]
    sha256 = "496bcf3667b990a04d8873f8785e709d36c56df34f38f4085e21310ea5ea07f2"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.x86_64-unknown-freebsd.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f5932e11c32366dfa413cf6248a244b8529a108"
os = "windows"

    [[GDAL.download]]
    sha256 = "4d35bb6012b98b6341bbb8818dd4c11514c3307ecbec9956fc954ce6895573d9"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.100+0/GDAL.v304.1200.100.x86_64-w64-mingw32-cxx11.tar.gz"
