[[GDAL]]
arch = "aarch64"
git-tree-sha1 = "9a25a7b13b539c4d339744c41ec41a3eae7d2b48"
os = "macos"

    [[GDAL.download]]
    sha256 = "a7563b8853393c1d48be258b252777c869a0b12b3392cc4720d83977dc10c47e"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.aarch64-apple-darwin.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e43fa803217844d03cb276faa18c45be4bcedcae"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "3565375c5c0e9d38ee3c270d1772bc2d6b409af4e63058f724968ba4df032c3b"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.aarch64-linux-gnu-cxx03.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f395305150d059d56a00c2f410d85b211621a7b"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "4b13230fed5c1d93928cefff6135686b83e6f1c53a18056e85c1988fcf78faf2"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.aarch64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89dcfe49ad111991dc65f922de5d9754a6ced106"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "756e42f199e5723d90ceb0a69003eb116a5ae2a35598f19069b9ddcca5eb3a5e"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.aarch64-linux-musl-cxx03.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd6bb4537c6daee3e18e74b1a97fb9cd2dbe087f"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "79cd5e9f9f00842d8c0741f04d476950eb65840d71b7e85cbaff9d3e3794f95c"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.aarch64-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "aarch64"
git-tree-sha1 = "3fa4bd4627ee9a61fac7d586cde6e04ced28e061"
os = "freebsd"

    [[GDAL.download]]
    sha256 = "b9066f69b198c314bee7a7378b7d58077326518cae4992cb4cd1c5f670dd6efb"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.aarch64-unknown-freebsd.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97bb81a27135d103dbd32d138acd1be7b79cb012"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "196a817ffb91753f5c8a1c061b0e01785b62429e32495d0246dff2b867a4b2fd"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39f430a4c2c8c8530280604497a4998959993cdb"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "be1453a369165b18063d25fa5e8ce943722ecae93293c200b8567bc1b5957667"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97562112557a294f3e6791aa48d4874f204bd5be"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "0986fdbed2e9e32742b8ad21611b55a02c98abf8c3e9576bc3bda5b995c92ca6"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82088c557967e7ac54b47a9d2160aa919e001e82"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "78772b3d69e605eaba86ba5ff30b827c4eaff5b2419603b961d2878b2b22c126"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14c47a2ea09fc8962a847534e33d2313376e2cc9"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "02af88201092c0d909551b8440bfd77ad8a2521ce38a81ca13298aec31d7c3df"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34867e15ce85b59272aa5085968e0ddb7e68fb7f"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "a2efe1bd3106ce250f1c29bd5e28cd80742398b1fe4d461fa8bac1d45f5326f2"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbcd73f295e2b987d12d0284fbc93c9132e9f9a9"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "9ea070260b0f52c9829105e4904bee193d0c62d78cefc24dca3be059fd42d3a8"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2974bb56272528ffe0cc82d909c8b6ddd036c79f"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "4836adacc3c6fab3e69b63dbde2c9389a4bab916ff2cb9671c1fa97d017035be"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cca44e3541d989dc54fb2052434959a4fdad087"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "6fdc9a14fa06d6454e92aab11a68efc9b03fa261e9a72fed25ec4d59ca85b462"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.i686-linux-gnu-cxx03.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e48d2aa63b79c076ab1488782a57073009169ec"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "75242cddf623aa83ce41b649b6a23a41e7cd97d5727ae5cfe3202d7c0a20281d"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.i686-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dedd4828e405481813282cca3c7b1f40dfea86a3"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "e6c70392f9f2224d8bf9a8b6a4016eb00514494b49a4525484a1109e61057425"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.i686-linux-musl-cxx03.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c7324531a36cd13ec9db36f9244119eefccef12"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "3a6ce706adcd72536fd60ad8382bbf530d8f2598db23c69a55cb6f8db1b20448"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.i686-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c621999334f8d152a910a776a07cb71ab371541"
os = "windows"

    [[GDAL.download]]
    sha256 = "4a9e7cf44ec3075e0c0bd12934564327c9e244f3251b761726f51bbb78a22d97"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.i686-w64-mingw32-cxx03.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0241f3d7a862de1c707fe47cce4ae92eadf4a6ad"
os = "windows"

    [[GDAL.download]]
    sha256 = "005656128deb801181505f52ee04f2194963d52222cce524371126c34b32bc03"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.i686-w64-mingw32-cxx11.tar.gz"
[[GDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e349779043479a20b12d6b3fc196b429fdfdea1a"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "c2b13effef4f860d069a661107db867032773e3b3a71f157332f97431f13b378"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c3565042552791303a6b84f8cbf5205702aeb99"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "411e12e538c8c4e5282647654374a5085581fa95ef060c5b65b94970a8960c18"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c0ae68bbfe131bdae0ed741eb17f1381bff1844"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "cad75bf8230270dcc3cd351c686305cc271f7d36a1e972caddae6aa00f1c0026"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.riscv64-linux-gnu-cxx03.tar.gz"
[[GDAL]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4cd1deb308a376deada7deebc4509c4de9e6e14"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "d889dc15bfa8e8837264e191a3f4ade76879f3f9f67abf62b5c87ac228f82430"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.riscv64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
git-tree-sha1 = "dbef0e7097b05feda1d4735d1eee22057e264295"
os = "macos"

    [[GDAL.download]]
    sha256 = "22744209f037f19970371063ec99f22afa6421e79c8f9dbbc6b7cce12cb7b1db"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.x86_64-apple-darwin.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c366ea34726d7e6b63d030e416cb26603da5cad"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "3007d8884c62d65fd42bc0692ce01e5dba53e4d2032bb756c8983d55d721151c"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.x86_64-linux-gnu-cxx03.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51099dcc6fc3500618d6f9858d690ee657b56e42"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "cded80589f4fe4ac10b0e1e6feacca6b88617ffc35d77c139b598866505b52a7"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.x86_64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "877069034f05d4f45884995c0cb46e3a16c1c1bf"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "bfa5cb14826e0381105acdccd33254f9a9260c7f2332b6993978a5fe22b94202"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.x86_64-linux-musl-cxx03.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eb2d58ac1a895416f3eac66ea29acfc53e43b7d"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "39072135e7528eb6b830e6de2d8213470558897f8d79a9b5a394f9a504d4c14e"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.x86_64-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
git-tree-sha1 = "8a64e0b213b06f2240a89e4c2bc90b9d94c637e6"
os = "freebsd"

    [[GDAL.download]]
    sha256 = "ef053daffb0ef46305e264b0522689c3beceea44f7a4500871399c93e17a22d6"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.x86_64-unknown-freebsd.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "145fbffc3858e48432072345cd57f56a64f8bd6d"
os = "windows"

    [[GDAL.download]]
    sha256 = "9d85276822c1125cf68320364e5c33a2b4005c355a3f6b67b6555b04ce239c8a"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.x86_64-w64-mingw32-cxx03.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "536775a0b76c766db4707349e2f2d664091519da"
os = "windows"

    [[GDAL.download]]
    sha256 = "bf046fdc2d0aa8a49393320a67f387bf96d269aa5edaf5bc459464dcf7eca95f"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.400+0/GDAL.v303.1100.400.x86_64-w64-mingw32-cxx11.tar.gz"
