[[GDAL]]
arch = "aarch64"
git-tree-sha1 = "51832bd4550d7bf0d370d32cf7bd233751e8a367"
os = "macos"

    [[GDAL.download]]
    sha256 = "31bb60e6e0cb64f7adb1e069dc3b6b01cb8ea2170a6f545c04f0bd2365f4a9eb"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.aarch64-apple-darwin.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bc698d52752f525bb6061eaaddd984d815e5c83"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "671a55e6c6186f3d2dc09c2eda53b78a8242d9adfa2ead7f25753a0339f8eb9a"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.aarch64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d797944363d844b5aea3612ec5b8f3ffbc05b08"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "acfc68d27d3ab4988513667fa8da2d308af60fe5c86454ceb2f5749a13a4c474"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.aarch64-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "aarch64"
git-tree-sha1 = "cd13036fbf4e95eb4e14054d98fcdc0c1b775dfa"
os = "freebsd"

    [[GDAL.download]]
    sha256 = "288bcfb6dcc72d2662a992cd6e4e94a8576ed076592d01face2ce6c2201f3bd3"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.aarch64-unknown-freebsd.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c7b6adb6796dc2821612e10a062ca7aa1adea13"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "5597097ef5b882cc6ea755961b3626881c55885dc80995693041010e2e3e3b17"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5023bf9b6224c8121db4df4f5587e9c1ba45a8c3"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "304100b235a5a3d525ebd84afbe89c3b6a445bcaa8c4b9cb3a4c7108d8ee3ce4"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "142a7fa43a9c98ca4c0c94de8b2fbc0815e07c1c"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "b7dbc3728f2954558d4fa07f23917f985401c88fcd65bbb94e9f2a21326f4166"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84e6e3431ea6fd246b3ad7ae1c149c75b9e56843"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "1294e8189162e9480e9119fa595d8ad18ef65b92b88d9774860d0f1b88d88ac6"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ced4dff44e50e3893f18782a4e1df00a3bc8717"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "814cbe1cebf448e0771693e3d0e9a9b56cf0901148ffc2e6e810baa027349753"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.i686-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5594451ce28e6655ca30763c248ed69142a5f285"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "999d1bcc198045e058cbfaca9fdd4cefd98e02e885970d5b561c75e11ce550a6"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.i686-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55b73a55a668d2924b78ddf83ae3cf20e9fa52af"
os = "windows"

    [[GDAL.download]]
    sha256 = "c2b511ae22860bd68a701a295260e16a97feedc2edfe74bd2540ffada0c43c8b"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.i686-w64-mingw32-cxx11.tar.gz"
[[GDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01a27c342ef2e81779b42b327169575920b3a0c6"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "0a03b4207188bc5f93bcb6dd918ec4b935c5725a2f3bd014304159a73fa68721"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4d7b00ca84787f99af3a9106537e56b5a82a2cc"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "3ff4510461cc7acf08ee6029b084eba8f4f3d763b91e101939b225466fe2157a"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.riscv64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
git-tree-sha1 = "2d5b40545a2a12ecc3bba93fbf815d8d08163cb5"
os = "macos"

    [[GDAL.download]]
    sha256 = "17de3adcd3f6b727f6564f481bb2c576a7c23d49687a0809edb794aab11d06f8"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.x86_64-apple-darwin.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a659999e239019c944de33ba062e2d3a14b0dce5"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "baf322589a894661cfdc7344ec929b38490e48da074cfd6439637d4a874b48e9"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.x86_64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee263811ee62fa2af5d26f917be5249a57a8b558"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "0c173ffa848ced400e8f455127e834de621dfc88b16d4979b23977d5c6b28903"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.x86_64-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
git-tree-sha1 = "6887e040dafe9217fef50376ca5e0db3ef74d683"
os = "freebsd"

    [[GDAL.download]]
    sha256 = "552deabd3fcdeb864ff34de06d41df8e21066c985172d483df7f379b1a736b8e"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.x86_64-unknown-freebsd.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "605a6f431bd3171cfb1a94e86380be0fd4f3a4f9"
os = "windows"

    [[GDAL.download]]
    sha256 = "22c84bcf47ce2d6f547df1178e66a856207bb7e012a4459eab2060d98cd854df"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v303.1100.500+0/GDAL.v303.1100.500.x86_64-w64-mingw32-cxx11.tar.gz"
